PE-234 - Add the Amazon CloudFront signed URLs endpoint.
proversity-org/secure-cloudfront-video pull request #2
Opened 2019-11-12 21:55 UTC by Squirrel18

## Description:

This PR adds a new endpoint to sign URLs related to any resource in Amazon CloudFront service.

## Previous work:

https://github.com/proversity-org/edx-platform/pull/1036

## Configure:

ENV_TOKENS:

- SCV_CLOUDFRONT_ID = 'your-cloudfront-project-id'
- SCV_CLOUDFRONT_URL = 'your-cloudfront-url-containing-the-slash-at-the-end'

AUTH_TOKENS

- SCV_CLOUDFRONT_PRIVATE_SIGNING_KEY = 'cloudfront-private-signing-key'

## Reviewers:

- [ ] @andrey-canon

2019-11-15 23:13 UTC, andrey-canon requested changes

2019-11-15 23:13 UTC, andrey-canon commented on secure_cloudfront_video/views.py
> +        GET lms-ur/secure-cloudfront-video/?key=path-to-aws-resource
```suggestion
        GET lms-url/secure-cloudfront-video/?key=path-to-aws-resource
```

2019-11-15 23:13 UTC, andrey-canon commented on secure_cloudfront_video/utils.py
> +        raise Http404
This is not a view and it should not raise an 404, use another exception a handle it on the view

2019-11-15 23:13 UTC, andrey-canon commented on secure_cloudfront_video/views.py
> +    if not (cloudfront_url or cloudfront_id):
@Squirrel18 I think this should be an `and` and you could merge this with the previous conditional
somethin llike   `if not (key and cloudfront_url and cloudfront_id):`

2019-11-15 23:13 UTC, andrey-canon commented on secure_cloudfront_video/views.py
> +        resource_url,
```suggestion
        url='{}{}'.format(cloudfront_url, key),
```

2019-11-15 23:13 UTC, andrey-canon commented on secure_cloudfront_video/utils.py
> +    return time_now + minute_delta
All these lines could be merged

2019-11-15 23:13 UTC, andrey-canon commented on secure_cloudfront_video/utils.py
> +        cloudfront_key,
```suggestion
        data=cloudfront_key,
```

2019-11-18 18:36 UTC, Squirrel18 commented on secure_cloudfront_video/views.py
> +        GET lms-ur/secure-cloudfront-video/?key=path-to-aws-resource
Addresed.

2019-11-18 18:37 UTC, Squirrel18 commented on secure_cloudfront_video/views.py
> +    if not (cloudfront_url or cloudfront_id):
Addresed.

2019-11-18 18:40 UTC, Squirrel18 commented on secure_cloudfront_video/utils.py
> +    return time_now + minute_delta
Addressed.

2019-11-18 18:42 UTC, Squirrel18 commented on secure_cloudfront_video/utils.py
> +        cloudfront_key,
Addressed.

2019-11-18 20:50 UTC, Squirrel18 commented on secure_cloudfront_video/utils.py
> +        raise Http404
Addressed.

2019-11-18 20:50 UTC, Squirrel18 commented on secure_cloudfront_video/views.py
> +        resource_url,
Addressed.

2019-11-18 21:33 UTC, andrey-canon approved these changes

2019-11-18 21:59 UTC, merged